local QueryBuilder = require("rio.database.query_builder")
local DBManager = require("rio.database.manager")

describe("Rio Query Builder", function()
    setup(function()
        DBManager.initialize({ adapter = "sqlite", database = ":memory:" })
    end)

    it("should build basic SELECT queries", function()
        local q = QueryBuilder.new():table("users"):select("id", "username"):where("active", true)
        local sql = q:toSql()
        assert.truthy(sql:find("SELECT id, username"))
        assert.truthy(sql:find("FROM users"))
        assert.truthy(sql:find("WHERE active ="))
    end)

    it("should handle various WHERE operators", function()
        local q = QueryBuilder.new():table("products")
            :where("price", ">", 100)
            :where("status", "!=", "deleted")
            :whereIn("category_id", {1, 2, 3})
        
        local sql = q:toSql()
        assert.truthy(sql:find("price > 100"))
        assert.truthy(sql:find("status != 'deleted'"))
        assert.truthy(sql:find("category_id IN %(1, 2, 3%)"))
    end)

    it("should support JOIN clauses", function()
        local q = QueryBuilder.new():table("posts")
            :select("posts.*", "users.username as author")
            :join("users", "posts.user_id", "=", "users.id")
        
        local sql = q:toSql()
        assert.truthy(sql:find("INNER JOIN users ON posts.user_id = users.id"))
    end)

    it("should handle ordering and pagination", function()
        local q = QueryBuilder.new():table("logs"):orderBy("created_at", "DESC"):limit(10):offset(20)
        local sql = q:toSql()
        assert.truthy(sql:find("ORDER BY created_at DESC"))
        assert.truthy(sql:find("LIMIT 10"))
        assert.truthy(sql:find("OFFSET 20"))
    end)
end)
