local luasql = require("luasql.sqlite3")
local env = luasql.sqlite3()
local conn = env:connect("repro_posts.sqlite3")

conn:execute("DROP TABLE IF EXISTS posts")
conn:execute([[
    CREATE TABLE posts (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        price INTEGER,
        body TEXT,
        published BOOLEAN,
        priority INTEGER,
        title TEXT
    )
]])

-- Use the EXACT SQL generated by QueryBuilder
local cur = conn:execute("SELECT * FROM posts WHERE id = 30 LIMIT 1")
print("Cursor for empty select: ", cur)
if cur then
    local row = cur:fetch(nil, "a")
    print("Row 1: ", row, type(row))
    if row then
        local count = 0
        for k, v in pairs(row) do count = count + 1 end
        print("  Col count: ", count)
    end
    cur:close()
end

conn:close()
env:close()
os.remove("repro_posts.sqlite3")
